# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_ref_81/fifo_ref_81.xci
# IP: The module: 'fifo_ref_81' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_ref_81/fifo_ref_81.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ref_81'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_ref_81/fifo_ref_81_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ref_81'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_ref_81/fifo_ref_81_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ref_81'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_ref_81/fifo_ref_81.xci
# IP: The module: 'fifo_ref_81' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_ref_81/fifo_ref_81.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ref_81'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_ref_81/fifo_ref_81_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ref_81'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_ref_81/fifo_ref_81_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ref_81'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
