# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param synth.incrementalSynthesisCache C:/Users/ramon/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-3236-DESKTOP-RAMON/incrSyn
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {Project 1-19}  -string {{CRITICAL WARNING: [Project 1-19] Could not find the file 'C:/Users/ramon/Documents/GITHUB/FPGA_BASED_RADAR_ACQUISITION_AND_PREPROCESSING_UNIT/FPGA_BASED_RADAR_ACQUISITION_AND_PREPROCESSING_UNIT.srcs/sources_1/ip/mig_axis/mig_a.prj'.}}  -suppress 
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.cache/wt [current_project]
set_property parent.project_path C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/new/migsdram.v
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/imports/rtl/wbm2axisp.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/imports/hdl/add_crc32.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/imports/hdl/add_preamble.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/imports/hdl/add_seq_num.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/new/control.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/new/debouncer.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/new/demux2.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/new/demux2_32b.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/new/dram.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/new/dram_control.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/imports/hdl/ethernet.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/new/ethernet_control.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/new/interface.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/new/memory.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/new/mux2.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/new/mux2_16b.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/imports/hdl/nibble_data.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/new/processing.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/imports/new/sd.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/new/sd_control.vhd
  C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/new/main.vhd
}
read_ip -quiet C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_ref_81/fifo_ref_81.xci
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_ref_81/fifo_ref_81.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_ref_81/fifo_ref_81_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_ref_81/fifo_ref_81_ooc.xdc]

read_ip -quiet C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_50_eth/fifo_50_eth.xci
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_50_eth/fifo_50_eth.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_50_eth/fifo_50_eth_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_50_eth/fifo_50_eth_ooc.xdc]

read_ip -quiet C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_81_eth/fifo_81_eth.xci
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_81_eth/fifo_81_eth.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_81_eth/fifo_81_eth_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_81_eth/fifo_81_eth_ooc.xdc]

read_ip -quiet C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/mig_7series/mig_7series.xci
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/mig_7series/mig_7series/user_design/constraints/mig_7series.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/mig_7series/mig_7series/user_design/constraints/mig_7series_ooc.xdc]

read_ip -quiet C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_81_50/fifo_81_50.xci
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_81_50/fifo_81_50.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_81_50/fifo_81_50_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/fifo_81_50/fifo_81_50_ooc.xdc]

read_ip -quiet C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/constrs_1/new/ARTY.xdc
set_property used_in_implementation false [get_files C:/Users/ramon/Documents/GITHUB/RADAR_PREPROCESSING_UNIT/RADAR_PREPROCESSING_UNIT.srcs/constrs_1/new/ARTY.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
