## CLOCK SIGNAL
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

## SWITCHES.
set_property -dict {PACKAGE_PIN A8 IOSTANDARD LVCMOS33} [get_ports sw_mode]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS33} [get_ports sw_resolution]
set_property -dict {PACKAGE_PIN A10 IOSTANDARD LVCMOS33} [get_ports rst]

## BUTTONS.
set_property -dict {PACKAGE_PIN D9 IOSTANDARD LVCMOS33} [get_ports btn_record]
set_property -dict {PACKAGE_PIN C9 IOSTANDARD LVCMOS33} [get_ports btn_save]
set_property -dict {PACKAGE_PIN B9 IOSTANDARD LVCMOS33} [get_ports btn_up]
set_property -dict {PACKAGE_PIN B8 IOSTANDARD LVCMOS33} [get_ports btn_down]

## SECURE DIGITAL (SD).
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS33} [get_ports o_cs]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33} [get_ports o_mosi]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS33} [get_ports i_miso]
set_property -dict {PACKAGE_PIN D12 IOSTANDARD LVCMOS33} [get_ports o_sclk]

## RADAR SIGNALS.
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports radar_clk]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports radar_trigger]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports radar_arming]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports clk_out]

## RADAR A/D.
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33} [get_ports {radar_din[0]}]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {radar_din[1]}]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports {radar_din[2]}]
set_property -dict {PACKAGE_PIN R12 IOSTANDARD LVCMOS33} [get_ports {radar_din[3]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {radar_din[4]}]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {radar_din[5]}]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {radar_din[6]}]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports {radar_din[7]}]
set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33} [get_ports {radar_din[8]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {radar_din[9]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {radar_din[10]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {radar_din[11]}]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports radar_overflow]

## ETHERNET
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS33} [get_ports i_eth_col]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33} [get_ports i_eth_crs]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports o_eth_mdc]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports io_eth_mdio]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports o_eth_ref_clk]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS33} [get_ports o_eth_rstn]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports i_eth_rx_clk]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports i_eth_rx_dv]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports {i_eth_rx_d[0]}]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports {i_eth_rx_d[1]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports {i_eth_rx_d[2]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports {i_eth_rx_d[3]}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33} [get_ports i_eth_rx_err]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports i_eth_tx_clk]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports o_eth_tx_en]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports {o_eth_tx_d[0]}]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {o_eth_tx_d[1]}]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports {o_eth_tx_d[2]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {o_eth_tx_d[3]}]

#DRAM
set_property -dict {PACKAGE_PIN K6 IOSTANDARD SSTL135} [get_ports {o_ddr_reset_n}]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD SSTL135} [get_ports {o_ddr_ras_n}]
set_property -dict {PACKAGE_PIN M4 IOSTANDARD SSTL135} [get_ports {o_ddr_cas_n}]
set_property -dict {PACKAGE_PIN P5 IOSTANDARD SSTL135} [get_ports {o_ddr_we_n}]
set_property -dict {PACKAGE_PIN U9 IOSTANDARD DIFF_SSTL135} [get_ports {o_ddr_ck_p[0]}]
set_property -dict {PACKAGE_PIN V9 IOSTANDARD DIFF_SSTL135} [get_ports {o_ddr_ck_n[0]}]
set_property -dict {PACKAGE_PIN N5 IOSTANDARD SSTL135} [get_ports {o_ddr_cke[0]}]
set_property -dict {PACKAGE_PIN U8 IOSTANDARD SSTL135} [get_ports {o_ddr_cs_n[0]}]     
set_property -dict {PACKAGE_PIN R5 IOSTANDARD SSTL135} [get_ports {o_ddr_odt[0]}]       
set_property -dict {PACKAGE_PIN R1 IOSTANDARD SSTL135} [get_ports {o_ddr_ba[0]}]  
set_property -dict {PACKAGE_PIN P4 IOSTANDARD SSTL135} [get_ports {o_ddr_ba[1]}]         
set_property -dict {PACKAGE_PIN P2 IOSTANDARD SSTL135} [get_ports {o_ddr_ba[2]}]         
set_property -dict {PACKAGE_PIN R2 IOSTANDARD SSTL135} [get_ports {o_ddr_addr[0]}]
set_property -dict {PACKAGE_PIN M6 IOSTANDARD SSTL135} [get_ports {o_ddr_addr[1]}]
set_property -dict {PACKAGE_PIN N4 IOSTANDARD SSTL135} [get_ports {o_ddr_addr[2]}]
set_property -dict {PACKAGE_PIN T1 IOSTANDARD SSTL135} [get_ports {o_ddr_addr[3]}]
set_property -dict {PACKAGE_PIN N6 IOSTANDARD SSTL135} [get_ports {o_ddr_addr[4]}]
set_property -dict {PACKAGE_PIN R7 IOSTANDARD SSTL135} [get_ports {o_ddr_addr[5]}]
set_property -dict {PACKAGE_PIN V6 IOSTANDARD SSTL135} [get_ports {o_ddr_addr[6]}]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD SSTL135} [get_ports {o_ddr_addr[7]}]
set_property -dict {PACKAGE_PIN R8 IOSTANDARD SSTL135} [get_ports {o_ddr_addr[8]}]
set_property -dict {PACKAGE_PIN V7 IOSTANDARD SSTL135} [get_ports {o_ddr_addr[9]}]
set_property -dict {PACKAGE_PIN R6 IOSTANDARD SSTL135} [get_ports {o_ddr_addr[10]}]
set_property -dict {PACKAGE_PIN U6 IOSTANDARD SSTL135} [get_ports {o_ddr_addr[11]}]
set_property -dict {PACKAGE_PIN T6 IOSTANDARD SSTL135} [get_ports {o_ddr_addr[12]}]
set_property -dict {PACKAGE_PIN T8 IOSTANDARD SSTL135} [get_ports {o_ddr_addr[13]}]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD SSTL135} [get_ports {o_ddr_dm[0]}]      
set_property -dict {PACKAGE_PIN U1 IOSTANDARD SSTL135} [get_ports {o_ddr_dm[1]}]
set_property -dict {PACKAGE_PIN N2 IOSTANDARD DIFF_SSTL135} [get_ports {io_ddr_dqs_p[0]}]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD DIFF_SSTL135} [get_ports {io_ddr_dqs_p[1]}]
set_property -dict {PACKAGE_PIN N1 IOSTANDARD DIFF_SSTL135} [get_ports {io_ddr_dqs_n[0]}]
set_property -dict {PACKAGE_PIN V2 IOSTANDARD DIFF_SSTL135} [get_ports {io_ddr_dqs_n[1]}]
set_property -dict {PACKAGE_PIN K5 IOSTANDARD SSTL135} [get_ports {io_ddr_data[0]}]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD SSTL135} [get_ports {io_ddr_data[1]}]   
set_property -dict {PACKAGE_PIN K3 IOSTANDARD SSTL135} [get_ports {io_ddr_data[2]}]
set_property -dict {PACKAGE_PIN L6 IOSTANDARD SSTL135} [get_ports {io_ddr_data[3]}]   
set_property -dict {PACKAGE_PIN M3 IOSTANDARD SSTL135} [get_ports {io_ddr_data[4]}]          
set_property -dict {PACKAGE_PIN M1 IOSTANDARD SSTL135} [get_ports {io_ddr_data[5]}] 
set_property -dict {PACKAGE_PIN L4 IOSTANDARD SSTL135} [get_ports {io_ddr_data[6]}] 
set_property -dict {PACKAGE_PIN M2 IOSTANDARD SSTL135} [get_ports {io_ddr_data[7]}] 
set_property -dict {PACKAGE_PIN V4 IOSTANDARD SSTL135} [get_ports {io_ddr_data[8]}]
set_property -dict {PACKAGE_PIN T5 IOSTANDARD SSTL135} [get_ports {io_ddr_data[9]}]
set_property -dict {PACKAGE_PIN U4 IOSTANDARD SSTL135} [get_ports {io_ddr_data[10]}]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD SSTL135} [get_ports {io_ddr_data[11]}]
set_property -dict {PACKAGE_PIN V1 IOSTANDARD SSTL135} [get_ports {io_ddr_data[12]}]
set_property -dict {PACKAGE_PIN T3 IOSTANDARD SSTL135} [get_ports {io_ddr_data[13]}]
set_property -dict {PACKAGE_PIN U3 IOSTANDARD SSTL135} [get_ports {io_ddr_data[14]}]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD SSTL135} [get_ports {io_ddr_data[15]}]